const header=document.querySelector('[data-header]');const progress=document.querySelector('.progress span');const menuButton=document.querySelector('.menu-button');const mobileMenu=document.querySelector('.mobile-menu');const reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const updateScroll=()=>{const y=window.scrollY;header?.classList.toggle('is-scrolled',y>24);const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=`${max?y/max*100:0}%`;if(!reduceMotion){const hero=document.querySelector('.hero-media');const scale=.96;if(hero)hero.style.transform=`scale(${scale}) translateY(${Math.min(y*.055,38)}px)`}};addEventListener('scroll',updateScroll,{passive:true});updateScroll();
menuButton?.addEventListener('click',()=>{const open=!menuButton.classList.contains('open');menuButton.classList.toggle('open',open);mobileMenu.classList.toggle('open',open);menuButton.setAttribute('aria-expanded',String(open));mobileMenu.setAttribute('aria-hidden',String(!open));document.body.style.overflow=open?'hidden':''});mobileMenu?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>menuButton.click()));
document.querySelectorAll('.nav-dropdown>a').forEach(toggle=>{toggle.setAttribute('aria-haspopup','true');toggle.setAttribute('aria-expanded','false');toggle.addEventListener('click',event=>{event.preventDefault();const menu=toggle.parentElement,open=!menu.classList.contains('open');document.querySelectorAll('.nav-dropdown.open').forEach(item=>item.classList.remove('open'));menu.classList.toggle('open',open);toggle.setAttribute('aria-expanded',String(open))})});document.addEventListener('click',event=>{if(!event.target.closest('.nav-dropdown'))document.querySelectorAll('.nav-dropdown.open').forEach(item=>{item.classList.remove('open');item.querySelector(':scope>a')?.setAttribute('aria-expanded','false')})});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const bikes={gtr:{image:'assets/gtr-black-silver-studio.png',alt:'Black and silver Gusto GTR road bicycle',tone:'studio',kicker:'Race platform',title:'GTR',line:'Immediate by design.',copy:'A precise road platform for fast group rides, long climbs and the moments when every input matters.',terrain:'Road / Race',character:'Direct / Fast',page:'gtr.html'},cobra:{image:'assets/cobra.jpg',alt:'Red Gusto Cobra road bicycle',tone:'ink',kicker:'Road platform',title:'Cobra',line:'Fast without the fuss.',copy:'A composed road bike with the pace for a hard ride and the manners for every kilometre around it.',terrain:'Road / Endurance',character:'Balanced / Fluid',page:'cobra.html'},gtg:{image:'assets/gtg-studio-v2.png',alt:'Green Gusto GTG gravel bicycle in a dark studio',tone:'studio',kicker:'Gravel platform',title:'GTG',line:'The long way, faster.',copy:'A gravel platform for open roads, rougher edges and the quieter reward of going further.',terrain:'Gravel / Mixed',character:'Stable / Capable',page:'gtg.html'}};
document.querySelectorAll('[data-bike]').forEach(button=>button.addEventListener('click',()=>{const data=bikes[button.dataset.bike];const stage=document.querySelector('[data-bike-stage]');const visual=stage.querySelector('.bike-visual');document.querySelectorAll('[data-bike]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-selected',String(b===button))});visual.classList.add('changing');setTimeout(()=>{const img=stage.querySelector('[data-bike-image]');img.alt=data.alt;visual.dataset.tone=data.tone;if(data.cutout){img.setAttribute('data-white-cutout','');img.addEventListener('load',()=>removeWhiteCanvas(img),{once:true})}else{img.removeAttribute('data-white-cutout')}img.src=data.image;stage.querySelector('.ghost-type').textContent=data.title;['kicker','title','line','copy','terrain','character'].forEach(key=>stage.querySelector(`[data-bike-${key}]`).textContent=data[key]);const link=stage.querySelector('[data-bike-link]');if(link){link.href=data.page;link.firstChild.textContent=`Explore ${data.title} `}visual.classList.remove('changing')},220)}));document.querySelectorAll('[data-year]').forEach(el=>el.textContent=new Date().getFullYear());

// Remove only the near-white canvas connected to an image edge, preserving white artwork inside the subject.
function removeWhiteCanvas(img){const w=img.naturalWidth,h=img.naturalHeight;if(!w||!h)return;const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0);const frame=ctx.getImageData(0,0,w,h),px=frame.data,seen=new Uint8Array(w*h),queue=[];const add=(x,y)=>{if(x<0||y<0||x>=w||y>=h)return;const n=y*w+x;if(seen[n])return;const i=n*4;if(px[i]>220&&px[i+1]>220&&px[i+2]>220){seen[n]=1;queue.push(n)}};for(let x=0;x<w;x++){add(x,0);add(x,h-1)}for(let y=0;y<h;y++){add(0,y);add(w-1,y)}for(let q=0;q<queue.length;q++){const n=queue[q],x=n%w,y=(n/w)|0,i=n*4;px[i+3]=0;add(x-1,y);add(x+1,y);add(x,y-1);add(x,y+1)}if(img.matches('[data-bike-image]')){for(let i=0;i<px.length;i+=4){const hi=Math.max(px[i],px[i+1],px[i+2]),lo=Math.min(px[i],px[i+1],px[i+2]);if(lo>180&&hi-lo<24)px[i+3]=lo>232?0:Math.min(px[i+3],Math.round((lo-180)/52*72))}}ctx.putImageData(frame,0,0);img.removeAttribute('data-white-cutout');img.src=canvas.toDataURL('image/png')}
document.querySelectorAll('[data-white-cutout]').forEach(img=>img.complete?removeWhiteCanvas(img):img.addEventListener('load',()=>removeWhiteCanvas(img),{once:true}));

const dealerSearch=document.querySelector('[data-dealer-search]');
if(dealerSearch){const cards=[...document.querySelectorAll('[data-dealer-card]')],count=document.querySelector('[data-dealer-count]'),empty=document.querySelector('[data-dealer-empty]');const filterDealers=()=>{const query=dealerSearch.value.trim().toLowerCase();let visible=0;cards.forEach(card=>{const match=!query||card.textContent.toLowerCase().includes(query);card.hidden=!match;if(match)visible++});count.textContent=`${visible} dealer${visible===1?'':'s'}`;empty.hidden=visible!==0};dealerSearch.addEventListener('input',filterDealers)}

const recurPrice=document.querySelector('[data-recur-price]');
const recurDeposit=document.querySelector('[data-recur-deposit]');
if(recurPrice&&recurDeposit){const pounds=value=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(value);const updateRecur=()=>{const price=Math.max(0,Number(recurPrice.value)||0);const deposit=Math.min(price,Math.max(0,Number(recurDeposit.value)||0));const future=Math.round(price*.45);const financed=Math.max(0,price-deposit-future);const monthly=Math.round(financed/24);document.querySelector('[data-recur-monthly]').textContent=pounds(monthly);document.querySelector('[data-recur-price-output]').textContent=pounds(price);document.querySelector('[data-recur-deposit-output]').textContent=pounds(deposit);document.querySelector('[data-recur-future]').textContent=pounds(future);document.querySelector('[data-recur-financed]').textContent=pounds(financed)};recurPrice.addEventListener('input',updateRecur);recurDeposit.addEventListener('input',updateRecur);updateRecur()}

const interestForm=document.querySelector('[data-interest-form]');
if(interestForm){interestForm.addEventListener('submit',async event=>{event.preventDefault();const status=interestForm.querySelector('[data-interest-status]');const button=interestForm.querySelector('button[type="submit"]');const buttonLabel=button.querySelector('span');button.disabled=true;buttonLabel.textContent='Sending…';status.textContent='';try{const response=await fetch(interestForm.action,{method:'POST',body:new FormData(interestForm),headers:{Accept:'application/json'}});if(!response.ok)throw new Error('Submission failed');interestForm.reset();buttonLabel.textContent='Interest registered';status.textContent='Thank you. Your details have been received and the Gusto UK team will be in touch.';status.classList.remove('is-error');status.classList.add('is-success')}catch(error){buttonLabel.textContent='Register my interest';status.textContent='We could not send your details. Please check your connection and try again.';status.classList.remove('is-success');status.classList.add('is-error');button.disabled=false;return}setTimeout(()=>{button.disabled=false;buttonLabel.textContent='Register my interest'},3500)})}
